[tool.uv.workspace]
members = ["packages/*"]
exclude = []

[tool.uv.sources]
agentsociety = { workspace = true }
agentsociety-community = { workspace = true }

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ruff>=0.11.13",
]
